services:
  spt-server:
    build:
      context: .
    image: spt-server:4.0.13
    container_name: spt-server
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${SPT_PORT:-6969}:${SPT_PORT:-6969}"
    volumes:
      - ./spt-user:/app/user
