name: spt-413
services:
  spt-server:
    build:
      context: .
    image: spt-server:4.1.3
    platform: linux/amd64
    restart: unless-stopped
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      SPT_IP: 0.0.0.0
      SPT_PORT: 6969
      SPT_BACKEND_IP: ${SPT_BACKEND_IP:-127.0.0.1}
      SPT_BACKEND_PORT: ${SPT_PORT:-6969}
    ports:
      - "${SPT_PORT:-6969}:6969"
    volumes:
      - ./spt-user:/app/user
